packages:
  - "orchestrator"
  - "worker"
  - "."

allowBuilds:
  '@prisma/engines': true
  '@whiskeysockets/baileys': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
