// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
config({ path: ".env.local", override: false });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI only (migrate / db commands) — NOT the app runtime, which uses
    // the pooled DATABASE_URL via the Neon adapter in src/lib/db.ts.
    // Migrations need a DIRECT (unpooled) connection: Neon's pooler endpoint
    // rejects the session-level connection `prisma migrate` makes (P1001).
    // Set DIRECT_URL to the unpooled host (same URL without `-pooler`).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
