ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "maxAgents" INT NOT NULL DEFAULT 1;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "category" TEXT;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "address" TEXT;
