ALTER TABLE "User" ALTER COLUMN "phone" DROP NOT NULL;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "businessCategory" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "businessDescription" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "businessAddress" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "businessEmail" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "businessWebsite" TEXT;
